version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/Services/RetailBankingServices/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    labels:
      - "dependencies"
      - "gradle"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 0
    labels:
      - "dependencies"
      - "github-actions"
