
replicaCount: 1

image:
  repository: 654654228171.dkr.ecr.us-east-1.amazonaws.com/books-ms-repo
  tag: tag
  pullPolicy: IfNotPresent

service:
  name: books-mgmt-service
  type: ClusterIP
  port: 9080
  containerPort: 9080

configMap:
  name: books-mgmt-app-config
  data:
    APP_CERT_STORE_PATH: /usr/lib/jvm/java-21-amazon-correttose/lib/security/cacerts
    spring.profiles.active: sit
    LIQUIBASE_CONTEXT: sit
    CONTAINER_PORT: 9080
    DB_URL: jdbc:postgresql://postgres.myapp.internal:5432/appdb
    

secret:
  name: books-mgmt-db-secret
  data:
    DB_UNAME: <<DB_UNAME>>
    DB_PASSWORD: <<DB_PASSWORD>>

resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "900m"
    memory: "3Gi"

truststore:
  javaHome: /usr/lib/jvm/java-21-amazon-corretto

ingress:
  enabled: true
  name: books-mgmt-ingress
  tls:
   secretName: books-mgmt-ingress-tls
   cert: |
     <<tls_cert>>
   key: |
     <<tls_key>>

host: "api-internal.books-service.internal"

paths:
  - path: /books-service
    pathType: Prefix
    service:
      name: books-mgmt-service
      port: 9080
