secrets:
  key_value_secrets:
    - name: "db_secrets"
      data:
        PROP_DEC_KEY: "xitCH2eLoXA8JMYR7LQQIpCLB1p-ovaDQKvlYHStM1s"
        DB_URL: "mib12-pre.cluster-cfyi5jk7hi11.eu-west-1.rds.amazonaws.com"
        DB_PORT: "4002"
        DB_NAME: "mib_ai_integration"
        DB_USERNAME: "kr8odp__wAkClRpaZ30poHbuA8MmdypSPtLQjERsD4Q"
        DB_PASSWORD: "kr8odp__wAkClRpaZ30poD1NZrkwY211wLiXF9S8QKs"
        DB_SCHEMA: "s_mib_ai_integration"
        ORACLE_DB_URL: "jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCPS)(HOST=konypre.cfyi5jk7hi11.eu-west-1.rds.amazonaws.com)(PORT=1721)))(CONNECT_DATA=(SID=KONYPRE)(SERVER=DEDICATED)))"
        ORACLE_DB_USERNAME: "RfWp38v_sqal-1S8UtFSlA"
        ORACLE_DB_PASSWORD: "RfWp38v_sqal-1S8UtFSlA"

    - name: "app_config"
      data:
        CLIENT_ID: "DBfkHAWVZX5vQ3Ox3-7iOEpj8J1MV63IgTf7vve-RFMejRW5N3CUsUJjGKg4SmQU"
        CLIENT_SECRET: "kpExmmy4USHg3SmHZMnES_Xncak7F4U3izJu7tV2EtJhcAmJNbcdoDnRnhZhLj8P"
  plaintext_secrets:
    - name: "tls_cert"
      value: |
        -----BEGIN CERTIFICATE-----
        Paste your certificate content in aws console
        -----END CERTIFICATE-----
    - name: "tls_key"
      value: |
        -----BEGIN PRIVATE KEY-----
        Paste your certificate content in aws console
        -----END PRIVATE KEY-----
