{{/*
  This is a Helm library partial for a Secret manifest.
  To use in a consuming chart, call:
    {{ include "mib-common.secret" . }}
  This file does not render any resources by itself.
*/}}
{{- define "mib-common.secret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secret.data }}
  {{ $key }}: "{{ $value }}"
{{- end }}
{{- end -}}