{{/*
  This is a Helm library partial for a ServiceAccount manifest.
  To use in a consuming chart, call:
    {{ include "books-common.serviceaccount" . }}
  This file does not render any resources by itself.
*/}}
{{- define "books-common.serviceaccount" -}}
{{- if and .Values.serviceaccount (hasKey .Values.serviceaccount "name") (not (eq .Values.serviceaccount.name nil)) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceaccount.name }}
  annotations:
    {{- if index .Values.serviceaccount "irsa-arn" }}
    eks.amazonaws.com/role-arn: {{ index .Values.serviceaccount "irsa-arn" }}
    {{- end }}
{{- end }}
{{- end -}}