{{/*
  This is a Helm library partial for a TLS Secret manifest.
  To use in a consuming chart, call:
    {{ include "mib-common.tls-secret" . }}
  This file does not render any resources by itself.
*/}}
{{- define "mib-common.tls-secret" -}}
{{- if and .Values.ingress.enabled (ne .Values.ingress.className "alb") }}
{{ if .Values.ingress.enabled }}
{{- $tls := .Values.ingress.tls | default dict -}}
{{- $secretName := $tls.secretName | default (printf "%s-ingress-tls" .Release.Name) -}}
{{- $tlsCert := $tls.cert | required "ERROR: .Values.ingress.tls.cert is required when tls is defined!" | b64enc -}}
{{- $tlsKey := $tls.key | required "ERROR: .Values.ingress.tls.key is required when tls is defined!" | b64enc -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $tlsCert }}
  tls.key: {{ $tlsKey }}
{{ end }}
{{- end -}}
{{- end -}}