{{/*
  This is a Helm library partial for a TLS Secret manifest.
  To use in a consuming chart, call:
    {{ include "books-common.truststore-secret" . }}
  This file does not render any resources by itself.
*/}}
{{- define "books-common.truststore-secret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-truststore
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  cacerts: {{ .Files.Get "files/combined-truststore.jks" | b64enc }}
{{- end -}}