{{- define "microservice.serviceAccount" -}}
{{- if.Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "microservice.serviceAccountName". }}
  namespace: {{.Release.Namespace }}
  labels:
    {{- include "microservice.labels". | nindent 4 }}
  annotations:
    {{- /* Automatically inject the AWS Role ARN if provided in values */}}
    {{- if.Values.serviceAccount.annotations }}
    {{- toYaml.Values.serviceAccount.annotations | nindent 4 }}
    {{- end }}
{{- end -}}
{{- end -}}