secrets:
  key_value_secrets:
    - name: "db_secrets"
      data:
        DB_USERNAME: "lTcW2na5YBVQAFzyWYo1SQ"
        DB_PASSWORD: "lTcW2na5YBVQAFzyWYo1SQ"
    - name: "app_config"
      data:
        CLIENT_ID: "DBfkHAWVZX5vQ3Ox3-7iOEpj8J1MV63IgTf7vve-RFMejRW5N3CUsUJjGKg4SmQU"
        CLIENT_SECRET: "kpExmmy4USHg3SmHZMnES_Xncak7F4U3izJu7tV2EtJhcAmJNbcdoDnRnhZhLj8P"
  plaintext_secrets:
    - name: "tls_cert"
      value: |
        -----BEGIN CERTIFICATE-----
        Paste your certificate content in aws console
        -----END CERTIFICATE-----
    - name: "tls_key"
      value: |
        -----BEGIN PRIVATE KEY-----
        Paste your certificate content in aws console
        -----END PRIVATE KEY-----