secrets:
  key_value_secrets:
    - name: "db_secrets"
      data:
        DB_USERNAME: "postgres"
        DB_PASSWORD: "postgres"
    - name: "app_config"
      data:
        CLIENT_ID: "TestClientID"
        CLIENT_SECRET: "TestClientSecret"
  plaintext_secrets:
    - name: "tls_cert"
      value: |
        -----BEGIN CERTIFICATE-----
        Paste your certificate content in aws console
        -----END CERTIFICATE-----
    - name: "tls_key"
      value: |
        -----BEGIN PRIVATE KEY-----
        Paste your certificate content in aws console
        -----END PRIVATE KEY-----