name: Deploy database script to environment
run-name: Deploy database scripts to ${{ inputs.environment }} - ${{ inputs.service_name }}

on:
  workflow_call:
    inputs:
      domain:
        required: true
        type: string
      environment:
        required: true
        type: string
      service_name:
        required: true
        type: string
      skip_env:
        required: true
        type: string
      runner:
        description: "Codebuild runner for the pipeline"
        default: codebuild-mib2-deafult-ubuntu-runner
        type: string
        required: false

permissions:
  contents: read
  id-token: write
  packages: write
  attestations: read

jobs:
  deploy:
    name: Deploy ${{ inputs.domain }}/${{ inputs.service_name }} to ${{ inputs.environment }}
    runs-on: ${{ inputs.runner }}-${{ github.run_id }}-${{ github.run_attempt }}
    environment: ${{ inputs.environment }}