name: PR – Secret Scanning Review

on:
  workflow_call:
    secrets:
      token:
        required: true
    inputs:
      service:
        description: "Service to scan"
        required: true
        type: string
    outputs:
      result:
        description: "Overall Secret Scanning result: success|failure"
        value: ${{ jobs.secret-scanning.outputs.result }}
jobs:
  secret-scanning:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      security-events: read


    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Run Secret Scanning
      - id: secret_scan
        name: Secret Scanning Review Action
        uses: advanced-security/secret-scanning-review-action@v2
        with:
          token: ${{ secrets.token }}
          fail-on-alert: true
          fail-on-alert-exclude-closed: true
          runtime: 'python'
        continue-on-error: true

      # Set job output for the main workflow
      - name: Set job output
        if: always()
        id: setoutput
        run: |
          echo "outcome=${{ steps.secret_scan.outcome }}"
          if [[ "${{ steps.secret_scan.outcome }}" == "failure" ]]; then
            echo "result=failure" >> $GITHUB_OUTPUT
          else
            echo "result=success" >> $GITHUB_OUTPUT
          fi

    outputs:
      result: ${{ steps.setoutput.outputs.result }}
