
name: Secret Scanning Review
on:
  workflow_call:
    inputs:
      fail-on-alert:
        description: 'Fail if any secret scanning alert is found'
        required: false
        default: true
        type: boolean
      fail-on-alert-exclude-closed:
        description: 'Fail if any open secret scanning alert is found (exclude closed)'
        required: false
        default: true
        type: boolean
      runtime:
        description: 'Runtime to use (python or powershell)'
        required: false
        default: ''
        type: string
      token:
        description: 'GitHub token with access to the secrets API'
        required: true
        type: string


permissions:
  contents: read
  pull-requests: read
  security-events: write # Required to dismiss alerts or post reviews

jobs:
  secret-scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
        with:
          fetch-depth: 0 # Full history
      - name: 'Secret Scanning Review Action'
        uses: advanced-security/secret-scanning-review-action@c8ac1ef693ea7d6c5f9367e82d0367dc78a12717 #v2.2.8
        with:
          token: ${{ inputs.token }}
          fail-on-alert: ${{ inputs.fail-on-alert }}
          fail-on-alert-exclude-closed: ${{ inputs.fail-on-alert-exclude-closed }}
          # Only set runtime if provided
          runtime: ${{ inputs.runtime }}