secrets:
  key_value_secrets:
    - name: "db_secrets"
      data:
        PROP_DEC_KEY: ""
        DB_URL: ""
        DB_PORT: ""
        DB_NAME: ""
        DB_USERNAME: ""
        DB_PASSWORD: ""
        DB_SCHEMA: ""
  plaintext_secrets:
    - name: "tls_cert"
      value: |
        -----BEGIN CERTIFICATE-----
        Paste your certificate content in aws console
        -----END CERTIFICATE-----
    - name: "tls_key"
      value: |
        -----BEGIN PRIVATE KEY-----
        Paste your certificate content in aws console
        -----END PRIVATE KEY-----